# Generated by Django 2.2.14 on 2021-03-30 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('cantidad', models.IntegerField()),
                ('medida', models.CharField(choices=[('lt', 'Litro'), ('gr', 'Gramo'), ('ml', 'Mililitro'), ('un', 'Unidad'), ('kg', 'Kilogramo')], default='gr', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('posicion', models.IntegerField(default=0)),
                ('descripcion', models.TextField(max_length=530)),
                ('tiempo', models.IntegerField()),
                ('preparacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Method')),
            ],
        ),
    ]
