# Generated by Django 2.2.14 on 2021-03-15 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pantry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kitchen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('precio', models.IntegerField()),
                ('init', models.IntegerField()),
                ('current', models.IntegerField()),
                ('medida', models.CharField(choices=[('lt', 'Litro'), ('gr', 'Gramo'), ('ml', 'Mililitro'), ('un', 'Unidad'), ('kg', 'Kilogramo')], default='gr', max_length=2)),
                ('pantry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pantry.Pantry')),
            ],
        ),
    ]
