# Generated by Django 2.2.14 on 2021-03-17 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0002_shoppingitem_shoppinglist'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='pantry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pantry.Pantry'),
        ),
    ]
